language: node_js
node_js:
  - "4"

sudo: required

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v
  - docker-compose -f docker-compose-test.yml build

script:
  - docker-compose -f docker-compose-test.yml run node run build
  - docker-compose -f docker-compose-test.yml run python
