elastic:
  image: elasticsearch

python:
  build: .
  dockerfile: Dockerfile-python
#  command: test
  links:
   - elastic
   - memcached
   - postgres

memcached:
  image: memcached

node:
  build: .
  dockerfile: Dockerfile-node
  command: test

postgres:
  image: postgres
