elastic:
  image: elasticsearch:1.6

memcached:
  image: memcached

node:
  build: .
  dockerfile: Dockerfile-node
  command: run build

postgres:
  build: ./postgres

python:
  build: .
  dockerfile: Dockerfile-python
  links:
   - elastic
   - node
   - memcached
   - postgres
   - rabbitmq
  volumes_from:
   - node

rabbitmq:
  image: rabbitmq
