FROM python:3.4

COPY ./requirements.txt ~/app/
COPY ./py ~/app/

WORKDIR ~/app

# Update the default application repository sources list
RUN apt-get update
RUN apt-get install -y libmemcached-dev

RUN pip --default-timeout=60 install -q -r requirements.txt

ENTRYPOINT ["nosetests", "test_connections.py"]
